version: '3.8'
services:
  api:
    build:
      context: ../src/Entrega_1_Regressão_Linear # Configura o contexto, no caso, volta pra pasta raiz, e entra na src/Entrega_1_Regressão_Linear
      dockerfile: api/Dockerfile # A partir do contexto, indica o caminho até o Dockerfile
    ports:
      - "80:80"